### ISSUE TITLE
Connect User Stories and Use Cases

### ISSUE THREAD

**Issue by Stensby** [CMPUT301W15T02/TeamTo#5]

**Comment by Stensby** [comment]
Christine and I have connected all of the UC and US except for those pertaining to Approval/Submission, as I am not sure if we should make another UC for the approval ones, as the viewing requirements are a little different.  (E.g. claims sorted by oldest-newest, and adding comments to expenses)

**Comment by rkdhatt** [comment]
Kyle sent Adam an email regarding that issue so we are just waiting for his response.

**Comment by kylecarlstrom** [comment]
I added some stuff for the approvers. Still waiting to here back on the tests.

**Comment by kylecarlstrom** [comment]
Adam got back to me on the tests. He said they looked good but that the test should correspond to use cases rather than user stories. I went ahead and cleaned up the comments so that it is clear about which tests correspond to which use cases. I also added a few more tests that are more system specific (e.g. filtering, sorting, etc.)
